// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candidates.sql

package db

import (
	"context"
)

const insertCandidate = `-- name: InsertCandidate :exec
INSERT OR IGNORE INTO wp_candidates (domain, hostname, sample_url)
VALUES (?, ?, ?)
`

type InsertCandidateParams struct {
	Domain    string `json:"domain"`
	Hostname  string `json:"hostname"`
	SampleUrl string `json:"sample_url"`
}

func (q *Queries) InsertCandidate(ctx context.Context, arg InsertCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertCandidate, arg.Domain, arg.Hostname, arg.SampleUrl)
	return err
}

const listCandidates = `-- name: ListCandidates :many
SELECT domain, hostname, sample_url
FROM wp_candidates
ORDER BY domain
`

func (q *Queries) ListCandidates(ctx context.Context) ([]WpCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WpCandidate
	for rows.Next() {
		var i WpCandidate
		if err := rows.Scan(&i.Domain, &i.Hostname, &i.SampleUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnverifiedDomains = `-- name: ListUnverifiedDomains :many
SELECT ac.domain
FROM (
    SELECT domain FROM wp_candidates
    UNION
    SELECT domain FROM disqus_candidates
) AS ac
LEFT JOIN results r ON ac.domain = r.domain
WHERE r.domain IS NULL
ORDER BY ac.domain
`

func (q *Queries) ListUnverifiedDomains(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnverifiedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
