// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disqus_candidates.sql

package db

import (
	"context"
)

const countScannedPartitions = `-- name: CountScannedPartitions :one
SELECT COUNT(*) AS cnt
FROM disqus_scan_progress
WHERE crawl = ?
`

func (q *Queries) CountScannedPartitions(ctx context.Context, crawl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScannedPartitions, crawl)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getMaxScannedPartition = `-- name: GetMaxScannedPartition :one
SELECT CAST(COALESCE(MAX(partition_idx), -1) AS INTEGER) AS max_idx
FROM disqus_scan_progress
WHERE crawl = ?
`

func (q *Queries) GetMaxScannedPartition(ctx context.Context, crawl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxScannedPartition, crawl)
	var max_idx int64
	err := row.Scan(&max_idx)
	return max_idx, err
}

const insertDisqusCandidate = `-- name: InsertDisqusCandidate :exec
INSERT OR IGNORE INTO disqus_candidates (domain, hostname, sample_url, disqus_shortname)
VALUES (?, ?, ?, ?)
`

type InsertDisqusCandidateParams struct {
	Domain          string `json:"domain"`
	Hostname        string `json:"hostname"`
	SampleUrl       string `json:"sample_url"`
	DisqusShortname string `json:"disqus_shortname"`
}

func (q *Queries) InsertDisqusCandidate(ctx context.Context, arg InsertDisqusCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertDisqusCandidate,
		arg.Domain,
		arg.Hostname,
		arg.SampleUrl,
		arg.DisqusShortname,
	)
	return err
}

const insertScanProgress = `-- name: InsertScanProgress :exec
INSERT OR REPLACE INTO disqus_scan_progress (crawl, partition_idx, partition_url, candidates_found)
VALUES (?, ?, ?, ?)
`

type InsertScanProgressParams struct {
	Crawl           string `json:"crawl"`
	PartitionIdx    int64  `json:"partition_idx"`
	PartitionUrl    string `json:"partition_url"`
	CandidatesFound int64  `json:"candidates_found"`
}

func (q *Queries) InsertScanProgress(ctx context.Context, arg InsertScanProgressParams) error {
	_, err := q.db.ExecContext(ctx, insertScanProgress,
		arg.Crawl,
		arg.PartitionIdx,
		arg.PartitionUrl,
		arg.CandidatesFound,
	)
	return err
}

const listDisqusCandidates = `-- name: ListDisqusCandidates :many
SELECT domain, hostname, sample_url, disqus_shortname
FROM disqus_candidates
ORDER BY domain
`

func (q *Queries) ListDisqusCandidates(ctx context.Context) ([]DisqusCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listDisqusCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisqusCandidate
	for rows.Next() {
		var i DisqusCandidate
		if err := rows.Scan(
			&i.Domain,
			&i.Hostname,
			&i.SampleUrl,
			&i.DisqusShortname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnverifiedDisqusDomains = `-- name: ListUnverifiedDisqusDomains :many
SELECT dc.domain
FROM disqus_candidates dc
LEFT JOIN results r ON dc.domain = r.domain
WHERE r.domain IS NULL
ORDER BY dc.domain
`

func (q *Queries) ListUnverifiedDisqusDomains(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnverifiedDisqusDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
