// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type DisqusCandidate struct {
	Domain          string `json:"domain"`
	Hostname        string `json:"hostname"`
	SampleUrl       string `json:"sample_url"`
	DisqusShortname string `json:"disqus_shortname"`
}

type DisqusScanProgress struct {
	Crawl           string `json:"crawl"`
	PartitionIdx    int64  `json:"partition_idx"`
	PartitionUrl    string `json:"partition_url"`
	CandidatesFound int64  `json:"candidates_found"`
	ScannedAt       string `json:"scanned_at"`
}

type Page struct {
	Domain               string `json:"domain"`
	PostID               int64  `json:"post_id"`
	Url                  string `json:"url"`
	Title                string `json:"title"`
	CommentCountInSample int64  `json:"comment_count_in_sample"`
}

type Result struct {
	Domain           string `json:"domain"`
	WpConfirmed      int64  `json:"wp_confirmed"`
	CommentsEndpoint int64  `json:"comments_endpoint"`
	CommentCountHint int64  `json:"comment_count_hint"`
	ApiRoot          string `json:"api_root"`
	Error            string `json:"error"`
}

type WpCandidate struct {
	Domain    string `json:"domain"`
	Hostname  string `json:"hostname"`
	SampleUrl string `json:"sample_url"`
}

type WpScanProgress struct {
	Crawl           string `json:"crawl"`
	PartitionIdx    int64  `json:"partition_idx"`
	PartitionUrl    string `json:"partition_url"`
	CandidatesFound int64  `json:"candidates_found"`
	ScannedAt       string `json:"scanned_at"`
}
