// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"
)

const listPages = `-- name: ListPages :many
SELECT domain, post_id, url, title, comment_count_in_sample
FROM pages
ORDER BY domain, comment_count_in_sample DESC
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.Domain,
			&i.PostID,
			&i.Url,
			&i.Title,
			&i.CommentCountInSample,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :exec
INSERT OR REPLACE INTO pages
    (domain, post_id, url, title, comment_count_in_sample)
VALUES (?, ?, ?, ?, ?)
`

type UpsertPageParams struct {
	Domain               string `json:"domain"`
	PostID               int64  `json:"post_id"`
	Url                  string `json:"url"`
	Title                string `json:"title"`
	CommentCountInSample int64  `json:"comment_count_in_sample"`
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage,
		arg.Domain,
		arg.PostID,
		arg.Url,
		arg.Title,
		arg.CommentCountInSample,
	)
	return err
}
