// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertCandidate(ctx context.Context, arg InsertCandidateParams) error
	InsertDisqusCandidate(ctx context.Context, arg InsertDisqusCandidateParams) error
	ListCandidates(ctx context.Context) ([]WpCandidate, error)
	ListConfirmedResults(ctx context.Context) ([]Result, error)
	ListDisqusCandidates(ctx context.Context) ([]DisqusCandidate, error)
	ListPages(ctx context.Context) ([]Page, error)
	ListResults(ctx context.Context) ([]Result, error)
	ListUnverifiedDisqusDomains(ctx context.Context) ([]string, error)
	ListUnverifiedDomains(ctx context.Context) ([]string, error)
	UpsertPage(ctx context.Context, arg UpsertPageParams) error
	UpsertResult(ctx context.Context, arg UpsertResultParams) error
}

var _ Querier = (*Queries)(nil)
