// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wp_scan_progress.sql

package db

import (
	"context"
)

const countWPScannedPartitions = `-- name: CountWPScannedPartitions :one
SELECT COUNT(*) AS cnt
FROM wp_scan_progress
WHERE crawl = ?
`

func (q *Queries) CountWPScannedPartitions(ctx context.Context, crawl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWPScannedPartitions, crawl)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getMaxWPScannedPartition = `-- name: GetMaxWPScannedPartition :one
SELECT CAST(COALESCE(MAX(partition_idx), -1) AS INTEGER) AS max_idx
FROM wp_scan_progress
WHERE crawl = ?
`

func (q *Queries) GetMaxWPScannedPartition(ctx context.Context, crawl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxWPScannedPartition, crawl)
	var max_idx int64
	err := row.Scan(&max_idx)
	return max_idx, err
}

const insertWPScanProgress = `-- name: InsertWPScanProgress :exec
INSERT OR REPLACE INTO wp_scan_progress (crawl, partition_idx, partition_url, candidates_found)
VALUES (?, ?, ?, ?)
`

type InsertWPScanProgressParams struct {
	Crawl           string `json:"crawl"`
	PartitionIdx    int64  `json:"partition_idx"`
	PartitionUrl    string `json:"partition_url"`
	CandidatesFound int64  `json:"candidates_found"`
}

func (q *Queries) InsertWPScanProgress(ctx context.Context, arg InsertWPScanProgressParams) error {
	_, err := q.db.ExecContext(ctx, insertWPScanProgress,
		arg.Crawl,
		arg.PartitionIdx,
		arg.PartitionUrl,
		arg.CandidatesFound,
	)
	return err
}
